import { json } from 'body-parser';
import compression from 'compression';
import cors from 'cors';
import express from 'express';
import helmet from 'helmet';
import morgan from 'morgan';
import { createStream } from 'rotating-file-stream';
import { serve, setup } from 'swagger-ui-express';
import { AuthRouter } from './api/auth/auth.router';
import { container } from './inversify.config';
import { INVERSIFY_TYPES } from './inversify.types';
import { expressRateLimitMiddleware } from './shared/middlewares/express-rate-limit.middleware';
import { globalErrorHandlerMiddleware } from './shared/middlewares/global-error-handler.middleware';
import { env } from './shared/utils/env';
import { buildOpenAPIDocument } from './shared/utils/zod-openapi/zod-openapi';
import { ErrorResponse } from './shared/utils/zod-openapi/zod-openapi.types';
require('express-async-errors');

// Server
const app = express();

// Middlewares
app.use(morgan('tiny'));
app.use(helmet());
app.use(cors({ origin: env.CORS_ORIGIN, credentials: true }));
app.use(expressRateLimitMiddleware);
app.use(compression());
app.use(json({ limit: '1mb' }));

// Log Retention
const accessLogStream = createStream('access.log', {
  path: env.LOG_PATH,
  interval: env.LOG_INTERVAL,
  maxFiles: env.LOG_MAX_FILES,
  size: env.LOG_MAX_SIZE
});
app.use(morgan('common', { stream: accessLogStream }));

// Load Routes
const authRouter = container.get<AuthRouter>(INVERSIFY_TYPES.AuthRouter);
const routers = [{ path: `${env.API_BASE_PATH}${authRouter.routerPath}`, router: authRouter.router }];
routers.forEach((e) => {
  app.use(e.path, e.router);
});

// Handle Swagger OpenAPI
const doc = buildOpenAPIDocument({
  routers,
  customSchemas: [{ key: 'ErrorResponse', schema: ErrorResponse }],
  securitySchemes: {
    bearerAuth: {
      type: 'http',
      scheme: 'bearer',
      bearerFormat: 'JWT'
    }
  },
  config: {
    openapi: '3.0.0',
    info: {
      version: '1.0.0',
      title: 'Express + Swagger + Zod API',
      description: `This OpenApi Swagger documentation is autogenerated from Zod Schemas!`
    }
  }
});
app.get(`${env.API_BASE_PATH}${env.SWAGGER_ENDPOINT}${env.SWAGGER_OPENAPI_DEF}`, (_req, res) => res.json(doc));
app.use(`${env.API_BASE_PATH}${env.SWAGGER_ENDPOINT}`, serve, setup(doc));
// TODO: Add basic auth to ${env.SWAGGER_ENDPOINT}

// Load Global Error Middleware last
app.use(globalErrorHandlerMiddleware);

export { app };
