import { json } from 'body-parser';
import compression from 'compression';
import cors from 'cors';
import express from 'express';
import helmet from 'helmet';
import morgan from 'morgan';
import { createStream } from 'rotating-file-stream';
import { serve, setup } from 'swagger-ui-express';
import { AuthController } from './api/auth/auth.controller';
import { MonitoringController } from './api/monitoring/monitoring.controller';
import { container } from './inversify.config';
import { INVERSIFY_TYPES } from './inversify.types';
import { env } from './lib/env';
import { buildOpenAPIDocument } from './lib/zod-openapi/zod-openapi';
import { ErrorResponse } from './lib/zod-openapi/zod-openapi.types';
import { basicAuthMiddleware } from './shared/middlewares/basic-auth.middleware';
import { expressRateLimitMiddleware } from './shared/middlewares/express-rate-limit.middleware';
import { globalErrorHandlerMiddleware } from './shared/middlewares/global-error-handler.middleware';
require('express-async-errors');

// Server
const app = express();

// Middlewares
app.use(morgan('tiny'));
app.use(helmet());
app.use(cors({ origin: env.CORS_ORIGIN, credentials: true }));
app.use(expressRateLimitMiddleware);
app.use(compression());
app.use(json({ limit: '1mb' }));

// Log Retention
const accessLogStream = createStream('access.log', {
  path: env.LOG_PATH,
  interval: env.LOG_INTERVAL,
  maxFiles: env.LOG_MAX_FILES,
  size: env.LOG_MAX_SIZE
});
app.use(morgan('common', { stream: accessLogStream }));

// Load Routes
const authController = container.get<AuthController>(INVERSIFY_TYPES.AuthController);
const monitoringController = container.get<MonitoringController>(INVERSIFY_TYPES.MonitoringController);
const routers = [
  { path: `${env.API_BASE_PATH}${authController.routerPath}`, router: authController.router },
  { path: `${env.API_BASE_PATH}${monitoringController.routerPath}`, router: monitoringController.router }
];
routers.forEach((e) => {
  app.use(e.path, e.router);
});

// Handle Swagger OpenAPI
const doc = buildOpenAPIDocument({
  routers,
  customSchemas: [{ key: 'ErrorResponse', schema: ErrorResponse }],
  securitySchemes: {
    bearerAuth: {
      type: 'http',
      scheme: 'bearer',
      bearerFormat: 'JWT'
    }
  },
  config: {
    openapi: '3.0.0',
    info: {
      version: '1.0.0',
      title: 'Express + Swagger + Zod API',
      description: `This OpenApi Swagger documentation is autogenerated from Zod Schemas!`
    }
  }
});
app.use(basicAuthMiddleware(env.SWAGGER_USERNAME, env.SWAGGER_PASSWORD, 'swagger', env.SWAGGER_ENDPOINT));
app.get(`${env.API_BASE_PATH}${env.SWAGGER_ENDPOINT}${env.SWAGGER_OPENAPI_DEF}`, (_req, res) => res.json(doc));
app.use(`${env.API_BASE_PATH}${env.SWAGGER_ENDPOINT}`, serve, setup(doc));

// Load Global Error Middleware last
app.use(globalErrorHandlerMiddleware);

export { app };
